name: masarak_driver
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1+3

environment:
  sdk: ^3.8.0

dependencies:
  awesome_dio_interceptor: ^1.3.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  go_router: ^16.2.0
  hooks_riverpod: ^2.6.1
  iconsax: ^0.0.8
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  top_snackbar_flutter: ^3.2.0
  wakelock_plus: ^1.3.2
  transporter:
    path: ../../packages/transporter
  driver:
    path: ../../packages/driver
  sub_app_core:
    git: https://github.com/devnoaman/sub_app_core.git
  api_client:
    git: https://github.com/devnoaman/api_client.git
  firebase_core: ^4.1.0
  pusher_channels_flutter: ^2.4.0
  # pusher_beams: ^1.1.2
  firebase_messaging: ^16.0.1
  pusher_beams: ^1.1.2
  # audioplayers: ^6.5.1
  sqflite: ^2.4.2
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/sounds/
  fonts:
    - family: GRAPHIK
      fonts:
        - asset: assets/fonts/GRAPHIK-ARABIC-BLACK.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-BOLD.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-EXTRALIGHT.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-LIGHT.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-MEDIUM.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-SEMIBOLD.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-THIN.otf
        - asset: assets/fonts/GRAPHIK-ARABIC.otf
    - family: Wahran
      fonts:
        - asset: assets/fonts/ArbFONTS-Wahran-Bold.otf
        - asset: assets/fonts/ArbFONTS-Wahran-Regular.otf
