name: transporter
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
# homepage:

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  hooks_riverpod: ^2.6.1
  sub_app_core:
    git: https://github.com/devnoaman/sub_app_core.git
  api_client:
    git: https://github.com/devnoaman/api_client.git
  shared:
    path: ../shared
  iconsax: ^0.0.8
  icons_font:
    path: ../icons_font
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  sliver_tools: ^0.2.12
  flutter_spinkit: ^5.2.2
  material_table_view: ^5.5.2
  easy_debouncer: ^0.0.2
  top_snackbar_flutter: ^3.3.0
  audioplayers: ^6.5.1
  flutter_animate: ^4.5.2
  # pusher_beams: ^1.1.2
  # freezed_annotation: ^3.1.0
  # json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  uuid: ^3.0.5
  # freezed: ^3.2.0
  # json_serializable: ^6.10.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:
# To add assets to your package, add an assets section, like this:
assets:
  - images/
#   - images/a_dot_ham.jpeg

#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
