name: masarak
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  # connectivity: ^3.0.6
  go_router: ^14.6.2
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  iconsax: ^0.0.8
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  awesome_dio_interceptor: ^1.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mobile_scanner: ^6.0.2
  wakelock_plus: ^1.2.10
  flutter_animate: ^4.5.2
  flutter_spinkit: ^5.2.1
  lottie: ^3.2.0
  flutter_secure_storage: ^9.2.2
  top_snackbar_flutter: ^3.1.0
  easy_debounce: ^2.0.3
  easy_stepper: ^0.8.5+1
  progress_stepper: ^3.1.0
  sqflite: ^2.4.1
  pretty_qr_code: ^3.3.0
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  audioplayers: ^6.1.1
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  
  # flutter_secure_storage: ^4.2.1
  # connectivity: ^3.0.6
  # connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  hive_ce_generator: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/sounds/
  fonts:
  - family: GRAPHIK
    fonts:
      - asset: assets/fonts/GRAPHIK-ARABIC-BLACK.otf
      - asset: assets/fonts/GRAPHIK-ARABIC-BOLD.otf
      - asset: assets/fonts/GRAPHIK-ARABIC-EXTRALIGHT.otf
      - asset: assets/fonts/GRAPHIK-ARABIC-LIGHT.otf
      - asset: assets/fonts/GRAPHIK-ARABIC-MEDIUM.otf
      - asset: assets/fonts/GRAPHIK-ARABIC-SEMIBOLD.otf
      - asset: assets/fonts/GRAPHIK-ARABIC-THIN.otf
      - asset: assets/fonts/GRAPHIK-ARABIC.otf
  - family: Alexandria
    fonts:
      - asset: assets/fonts/alexandria/Alexandria-Black.ttf  
      - asset: assets/fonts/alexandria/Alexandria-Bold.ttf  
      - asset: assets/fonts/alexandria/Alexandria-ExtraBold.ttf  
      - asset: assets/fonts/alexandria/Alexandria-ExtraLight.ttf  
      - asset: assets/fonts/alexandria/Alexandria-Light.ttf  
      - asset: assets/fonts/alexandria/Alexandria-Medium.ttf  
      - asset: assets/fonts/alexandria/Alexandria-Regular.ttf  
      - asset: assets/fonts/alexandria/Alexandria-SemiBold.ttf  
      - asset: assets/fonts/alexandria/Alexandria-Thin.ttf  

  # fonts:
  #   - family: IBMPlexSans
  #     fonts:
  #       - asset: assets/fonts/IBMPlexSans-Bold.ttf
  #         weight: 900
  #       - asset: assets/fonts/IBMPlexSans-Bold.ttf
  #         weight: 800
  #       - asset: assets/fonts/IBMPlexSans-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/IBMPlexSans-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/IBMPlexSans-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/IBMPlexSans-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/IBMPlexSans-Thin.ttf
  #         weight: 100  
  
