name: masarak_transporter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  # connectivity: ^3.0.6
  go_router: ^14.6.2
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  iconsax: ^0.0.8
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  awesome_dio_interceptor: ^1.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mobile_scanner: ^6.0.2
  wakelock_plus: ^1.2.10
  flutter_animate: ^4.5.2
  flutter_spinkit: ^5.2.1
  lottie: ^3.2.0
  flutter_secure_storage: ^9.2.2
  top_snackbar_flutter: ^3.1.0
  intl: ^0.20.2
  api_client:
    git: https://github.com/devnoaman/api_client.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
  fonts:
    - family: GRAPHIK
      fonts:
        - asset: assets/fonts/GRAPHIK-ARABIC-BLACK.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-BOLD.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-EXTRALIGHT.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-LIGHT.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-MEDIUM.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-SEMIBOLD.otf
        - asset: assets/fonts/GRAPHIK-ARABIC-THIN.otf
        - asset: assets/fonts/GRAPHIK-ARABIC.otf
